name: Run UFT One Tests

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

env:
  PROPS_TXT: PropsMultiTests.txt
  RES_XML: ResultsMultiTests.xml
  LAUNCHER_EXE: FTToolsLauncher.exe
  LAUNCHER_URL: https://github.com/MicroFocus/ADM-FT-ToolsLauncher/releases/download/v1.0-beta-rev12/FTToolsLauncher_net48.exe

defaults:
  run:
    shell: pwsh
    working-directory: ..\\

jobs:
  getUftTests:
    runs-on: self-hosted
    steps:
      - name: Display working directory
        run: echo "$pwd"

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          clean: false

  createPropsFile:
    runs-on: self-hosted
    needs: getUftTests
    steps:
      - name: Create properties file
        run: |
          @"runType=FileSystem
          Test1=$($pwd.Path.Replace('\\', '\\\\'))\MyTest" | Out-File $env:PROPS_TXT

  runUftTests:
    runs-on: self-hosted
    needs: createPropsFile
    steps:
      - name: Download FTToolsLauncher
        run: Invoke-WebRequest -Uri $env:LAUNCHER_URL -OutFile $env:LAUNCHER_EXE

      - name: Run UFT Tests
        run: .\$env:LAUNCHER_EXE -paramfile $env:PROPS_TXT -report $env:RES_XML
